const { formatPrice } = require('./format');

const CATEGORIES = [
  { id: 'all', name: '全部' },
  { id: 'main', name: '主食' },
  { id: 'snack', name: '小吃' },
  { id: 'drink', name: '饮品' },
  { id: 'dessert', name: '甜点' },
];

const RAW_MENU_ITEMS = [
  {
    id: 'm001',
    category: 'main',
    categoryName: '主食',
    name: '小熊蛋包饭',
    desc: '嫩滑蛋皮、番茄炒饭和清甜玉米粒。',
    price: 2600,
    unit: '份',
    tag: '招牌',
    art: 'rice',
    themeBg: '#FFE7A6',
    themeAccent: '#FF986E',
  },
  {
    id: 'm002',
    category: 'main',
    categoryName: '主食',
    name: '云朵咖喱饭',
    desc: '微甜咖喱、土豆胡萝卜和松软米饭。',
    price: 2800,
    unit: '份',
    tag: '人气',
    art: 'rice',
    themeBg: '#F8D7A4',
    themeAccent: '#D9824B',
  },
  {
    id: 'm003',
    category: 'main',
    categoryName: '主食',
    name: '番茄肉酱意面',
    desc: '酸甜番茄底，肉酱浓郁但不油腻。',
    price: 3000,
    unit: '份',
    tag: '',
    art: 'noodle',
    themeBg: '#FFD0CF',
    themeAccent: '#E85F5C',
  },
  {
    id: 'm004',
    category: 'main',
    categoryName: '主食',
    name: '菌菇鲜蔬面',
    desc: '菌菇汤底搭配青菜和溏心蛋。',
    price: 2400,
    unit: '碗',
    tag: '清爽',
    art: 'noodle',
    themeBg: '#DDEFC8',
    themeAccent: '#63A67A',
  },
  {
    id: 's001',
    category: 'snack',
    categoryName: '小吃',
    name: '香酥鸡块',
    desc: '外层酥脆，内里多汁，配自制酸甜酱。',
    price: 1800,
    unit: '份',
    tag: '热卖',
    art: 'snack',
    themeBg: '#FFE1B5',
    themeAccent: '#E49B3F',
  },
  {
    id: 's002',
    category: 'snack',
    categoryName: '小吃',
    name: '芝士薯角',
    desc: '烤薯角撒芝士粉，适合一起分享。',
    price: 1600,
    unit: '份',
    tag: '',
    art: 'snack',
    themeBg: '#FFEAB8',
    themeAccent: '#E1B340',
  },
  {
    id: 's003',
    category: 'snack',
    categoryName: '小吃',
    name: '玉米热狗棒',
    desc: '甜玉米粒包裹热狗，外皮松软。',
    price: 1500,
    unit: '支',
    tag: '',
    art: 'snack',
    themeBg: '#F6D9F0',
    themeAccent: '#C96AAE',
  },
  {
    id: 'd001',
    category: 'drink',
    categoryName: '饮品',
    name: '蜜桃气泡水',
    desc: '蜜桃果香、轻盈气泡和薄荷清香。',
    price: 1400,
    unit: '杯',
    tag: '冰',
    art: 'drink',
    themeBg: '#FFD9E3',
    themeAccent: '#F06F9A',
  },
  {
    id: 'd002',
    category: 'drink',
    categoryName: '饮品',
    name: '青柠茉莉茶',
    desc: '茉莉茶香加青柠，少糖也好喝。',
    price: 1300,
    unit: '杯',
    tag: '',
    art: 'drink',
    themeBg: '#CFEFDB',
    themeAccent: '#4AA783',
  },
  {
    id: 'd003',
    category: 'drink',
    categoryName: '饮品',
    name: '可可牛乳',
    desc: '温热可可和顺滑牛乳，口感柔和。',
    price: 1600,
    unit: '杯',
    tag: '热',
    art: 'drink',
    themeBg: '#D8C7B8',
    themeAccent: '#7C5F55',
  },
  {
    id: 't001',
    category: 'dessert',
    categoryName: '甜点',
    name: '草莓布丁杯',
    desc: '奶香布丁、草莓酱和脆脆谷物。',
    price: 1800,
    unit: '杯',
    tag: '新品',
    art: 'dessert',
    themeBg: '#FFD3D5',
    themeAccent: '#EF6C74',
  },
  {
    id: 't002',
    category: 'dessert',
    categoryName: '甜点',
    name: '焦糖小饼',
    desc: '焦糖香气浓，适合配茶或咖啡。',
    price: 1200,
    unit: '份',
    tag: '',
    art: 'dessert',
    themeBg: '#F1D0A8',
    themeAccent: '#B56F3D',
  },
];

const MENU_ITEMS = RAW_MENU_ITEMS.map(function mapItem(item) {
  return Object.assign({}, item, {
    priceText: formatPrice(item.price),
  });
});

function getMenuItem(id) {
  return MENU_ITEMS.find(function findItem(item) {
    return item.id === id;
  });
}

module.exports = {
  CATEGORIES,
  MENU_ITEMS,
  getMenuItem,
};
